import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import Icon from '../components/Icon';

export default function Profile() {
  const { user, updateProfile, logout } = useAuth();
  const navigate = useNavigate();
  const [message, setMessage] = useState('');
  const submit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); await updateProfile({ name: values.name, email: values.email, phone: values.phone, address: { street: values.street, city: values.city, province: values.province, postalCode: values.postalCode, country: values.country } }); setMessage('Your profile is up to date.'); };
  return <main className="page page-tight"><div className="page-heading"><p className="eyebrow">Your account</p><h1>Profile.</h1><p>Update your details, address, and preferences in one place.</p></div><section className="profile-layout"><aside className="profile-intro"><div className="profile-avatar">{user?.name?.slice(0, 1).toUpperCase()}</div><h2>{user?.name}</h2><p>{user?.email}</p><button className="button button-secondary button-small" onClick={() => { logout(); navigate('/'); }}><Icon name="logout" /> Sign out</button></aside><form className="form-card" onSubmit={submit}><h2>Personal details</h2><div className="form-grid"><div className="field full"><label htmlFor="name">Full name</label><input id="name" name="name" defaultValue={user?.name} required /></div><div className="field full"><label htmlFor="email">Email</label><input id="email" name="email" type="email" defaultValue={user?.email} required /></div><div className="field full"><label htmlFor="phone">Phone</label><input id="phone" name="phone" defaultValue={user?.phone} placeholder="+92 300 0000000" /></div></div><div className="form-section"><h3>Saved address</h3><div className="form-grid"><div className="field full"><label htmlFor="street">Street address</label><input id="street" name="street" defaultValue={user?.address?.street} placeholder="12 Garden Street" /></div><div className="field"><label htmlFor="city">City</label><input id="city" name="city" defaultValue={user?.address?.city} placeholder="Lahore" /></div><div className="field"><label htmlFor="province">Province</label><input id="province" name="province" defaultValue={user?.address?.province} placeholder="Punjab" /></div><div className="field"><label htmlFor="postalCode">Postal code</label><input id="postalCode" name="postalCode" defaultValue={user?.address?.postalCode} placeholder="54000" /></div><div className="field"><label htmlFor="country">Country</label><input id="country" name="country" defaultValue={user?.address?.country || 'Pakistan'} /></div></div></div>{message && <p className="field-error" style={{ color: 'var(--success)' }}>{message}</p>}<div className="form-actions"><button className="button" type="submit">Save changes <Icon name="check" /></button></div></form></section></main>;
}
