import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api from '../../api/axios';
import { demoCategories } from '../../data/demoData';
import Icon from '../../components/Icon';

export default function CreateProduct() {
  const [categories, setCategories] = useState(demoCategories); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const navigate = useNavigate();
  useEffect(() => { api.get('/categories').then(({ data }) => { if (!Array.isArray(data)) throw new Error('The API returned an invalid category collection.'); setCategories(data); }).catch(() => {}); }, []);
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api.post('/products', { ...values, imageUrls: JSON.stringify([values.imageUrl]) }); navigate('/admin/products'); } catch (requestError) { setError(requestError.response?.data?.message || 'Product could not be created.'); } finally { setSaving(false); } };
  return <main className="page page-tight"><div className="breadcrumbs"><Link to="/admin/products">Products</Link><span>/</span><span>Create</span></div><div className="page-heading"><p className="eyebrow">Catalog management</p><h1>Add a product.</h1><p>Bring a new, well-considered object into the edit.</p></div><form className="form-card" onSubmit={submit}><div className="form-grid"><div className="field full"><label htmlFor="name">Product name</label><input id="name" name="name" required minLength="3" placeholder="Orbit Chronograph" /></div><div className="field full"><label htmlFor="description">Description</label><textarea id="description" name="description" required minLength="20" placeholder="Describe the product with useful, honest detail." /></div><div className="field"><label htmlFor="price">Price</label><input id="price" name="price" type="number" min="0" required placeholder="189" /></div><div className="field"><label htmlFor="stock">Stock</label><input id="stock" name="stock" type="number" min="0" required placeholder="10" /></div><div className="field"><label htmlFor="category">Category</label><select id="category" name="category" required>{categories.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></div><div className="field"><label htmlFor="brand">Brand</label><input id="brand" name="brand" placeholder="Mera Studio" /></div><div className="field full"><label htmlFor="imageUrl">Product image URL</label><input id="imageUrl" name="imageUrl" type="url" required placeholder="https://images.unsplash.com/..." /></div><div className="field"><label htmlFor="isFeatured">Featured</label><select id="isFeatured" name="isFeatured"><option value="false">No</option><option value="true">Yes</option></select></div></div>{error && <p className="field-error">{error}</p>}<div className="form-actions"><button className="button" disabled={saving}>{saving ? 'Saving product' : 'Create product'} <Icon name="check" /></button></div></form></main>;
}
