import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import api from '../../api/axios';
import Loader from '../../components/Loader';
import Icon from '../../components/Icon';

const demoStats = { totalRevenue: 24860, totalOrders: 184, totalProducts: 42, totalCustomers: 1260 };
const demoRevenue = [{ month: 'Jan', revenue: 2900 }, { month: 'Feb', revenue: 4100 }, { month: 'Mar', revenue: 3600 }, { month: 'Apr', revenue: 5200 }, { month: 'May', revenue: 4700 }, { month: 'Jun', revenue: 6100 }];

export default function Dashboard() {
  const [stats, setStats] = useState(demoStats); const [revenue, setRevenue] = useState(demoRevenue); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([api.get('/admin/stats'), api.get('/admin/revenue-chart')]).then(([statsResponse, revenueResponse]) => { setStats(statsResponse.data); setRevenue(revenueResponse.data.length ? revenueResponse.data.map((item) => ({ month: item.month.slice(5), revenue: item.revenue })) : demoRevenue); }).catch(() => {}).finally(() => setLoading(false)); }, []);
  if (loading) return <Loader label="Loading the admin studio" />;
  return <main className="page page-tight"><section className="admin-layout"><aside className="admin-sidebar"><h2>Studio desk</h2><p>Manage the store with a clear view of the essentials.</p><Link className="admin-tab active" to="/admin">Overview</Link><Link className="admin-tab" to="/admin/products">Products</Link><Link className="admin-tab" to="/admin/orders">Orders</Link><Link className="admin-tab" to="/admin/users">Customers</Link></aside><div className="admin-content"><p className="eyebrow">Admin console</p><h1>Good morning, studio.</h1><p className="subtle">A calm view of the shop, ready for the next decision.</p><div className="stat-grid"><div className="stat-card"><span>Total revenue</span><strong>${stats.totalRevenue.toLocaleString()}</strong><small>Paid orders only</small></div><div className="stat-card"><span>Total orders</span><strong>{stats.totalOrders}</strong><small>Across every status</small></div><div className="stat-card"><span>Products</span><strong>{stats.totalProducts}</strong><small>Live catalog</small></div><div className="stat-card"><span>Customers</span><strong>{stats.totalCustomers}</strong><small>Registered accounts</small></div></div><div className="admin-grid"><section className="admin-panel"><div className="section-heading" style={{ marginBottom: 8 }}><h2>Revenue, last 6 months</h2><Icon name="chart" /></div><div className="dashboard-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={revenue} margin={{ top: 15, right: 8, left: -16, bottom: 0 }}><CartesianGrid vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} tickFormatter={(value) => `$${value / 1000}k`} /><Tooltip content={<div />} /><Bar dataKey="revenue" fill="#D16F55" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="admin-panel"><h2>Recent activity</h2><div className="activity-list"><div className="activity-item"><div><strong>New order received</strong><span>Orbit Chronograph</span></div><time>12 min</time></div><div className="activity-item"><div><strong>Product review posted</strong><span>Studio One Headphones</span></div><time>38 min</time></div><div className="activity-item"><div><strong>Low stock alert</strong><span>Signal Pro Phone</span></div><time>1 hr</time></div><div className="activity-item"><div><strong>New customer joined</strong><span>Welcome to Mera Store</span></div><time>2 hr</time></div></div></section></div><div className="hero-actions"><Link className="button" to="/admin/products/create">Add a product <Icon name="plus" /></Link><Link className="button button-secondary" to="/admin/orders">Review orders <Icon name="arrow" /></Link></div></div></section></main>;
}
