import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import api from '../../api/axios';
import { demoCategories, demoProducts } from '../../data/demoData';
import Loader from '../../components/Loader';
import Icon from '../../components/Icon';

export default function EditProduct() {
  const { id } = useParams(); const navigate = useNavigate(); const [product, setProduct] = useState(null); const [categories, setCategories] = useState(demoCategories); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.get(`/products/${id}`), api.get('/categories')]).then(([productResponse, categoryResponse]) => { if (!productResponse?.data || typeof productResponse.data !== 'object' || !productResponse.data._id || !Array.isArray(categoryResponse?.data)) throw new Error('The API returned invalid product data.'); setProduct(productResponse.data); setCategories(categoryResponse.data); }).catch(() => { setProduct(demoProducts.find((item) => item._id === id) || demoProducts[0]); }).finally(() => {}); }, [id]);
  if (!product) return <Loader label="Loading product" />;
  const submit = async (event) => { event.preventDefault(); setSaving(true); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api.put(`/products/${id}`, { ...values, imageUrls: JSON.stringify([values.imageUrl]) }); navigate('/admin/products'); } catch (requestError) { setError(requestError.response?.data?.message || 'Product could not be updated.'); } finally { setSaving(false); } };
  return <main className="page page-tight"><div className="breadcrumbs"><Link to="/admin/products">Products</Link><span>/</span><span>Edit</span></div><div className="page-heading"><p className="eyebrow">Catalog management</p><h1>Edit product.</h1></div><form className="form-card" onSubmit={submit}><div className="form-grid"><div className="field full"><label htmlFor="name">Product name</label><input id="name" name="name" defaultValue={product.name} required /></div><div className="field full"><label htmlFor="description">Description</label><textarea id="description" name="description" defaultValue={product.description} required minLength="20" /></div><div className="field"><label htmlFor="price">Price</label><input id="price" name="price" type="number" defaultValue={product.price} required /></div><div className="field"><label htmlFor="stock">Stock</label><input id="stock" name="stock" type="number" defaultValue={product.stock} required /></div><div className="field"><label htmlFor="category">Category</label><select id="category" name="category" defaultValue={product.category?._id}>{categories.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></div><div className="field"><label htmlFor="brand">Brand</label><input id="brand" name="brand" defaultValue={product.brand} /></div><div className="field full"><label htmlFor="imageUrl">Product image URL</label><input id="imageUrl" name="imageUrl" type="url" defaultValue={product.images?.[0]} required /></div></div>{error && <p className="field-error">{error}</p>}<div className="form-actions"><button className="button" disabled={saving}>{saving ? 'Saving changes' : 'Save changes'} <Icon name="check" /></button></div></form></main>;
}
